cors:
    originPatterns: http://localhost:3000,http://localhost:8080,https://localhost:8080
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cbo_database?allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=GMT-3&useSSL=false
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: true
springdoc:
  paths-to-match:
      - /auth/**
      - /api/**/v1/**
  swagger-ui:
    use-root-path: true
